### ISSUE TITLE
Assertion `strlen(c)+strlen(f->s) < n' failed.

### ISSUE THREAD

**Issue by keck-in-space** [nimble-code/Cobra#3]
When running Cobra with the following command

`cobra -v -f p10 *.[ch]`

I get

```
cobra: cobra_prim.c:236: check_args: Assertion `strlen(c)+strlen(f->s) < n' failed.
Aborted (core dumped)
```

**Comment by nimble-code** [comment]
I'll check it out -- thanks for reporting this!
-g

**Comment by nimble-code** [comment]
i cannot reproduce this error -- i tried on Windows and on Ubuntu linux.
what platform did you use when you saw this problem?

**Comment by keck-in-space** [comment]
Ah. That could be the issue. I'm running Ubuntu in Windows Subsystem for Linux on Windows 10.

**Comment by keck-in-space** [comment]
If it's useful to you I ran all of predefined checks and here's a list of the predefined checks that have the error.

- cobra_iridex.txt:cobra: cobra_prim.c:236: check_args: Assertion `strlen(c)+strlen(f->s) < n' failed.
- cobra_jpl.txt:cobra: cobra_prim.c:236: check_args: Assertion `strlen(c)+strlen(f->s) < n' failed.
- cobra_p10.txt:cobra: cobra_prim.c:236: check_args: Assertion `strlen(c)+strlen(f->s) < n' failed.
- cobra_reverse_null.txt:cobra: cobra_prim.c:236: check_args: Assertion `strlen(c)+strlen(f->s) < n' failed.

The JPL and P10 checks get somewhat far before having the issue. I may switch to Cygwin so I can run this without error for now and if I do I'll let you know if I see the issue again.

Thank you

**Comment by keck-in-space** [comment]
I just tested this with Cygwin and got the same error. Perhaps its something in the code I'm analyzing.

**Comment by nimble-code** [comment]
is it always in the same file, and does it also give the error if you give it just that one file?
I'm running a newer version of Cobra, so it could be that this is something that I fixed before.
I'll retest with the version from the distribution though. (I tried it on the cobra sources themselves and didn't see the assertion failure happening.

**Comment by keck-in-space** [comment]
It appears to occur in multiple files in the source, but not in every file. Every time I give it those specific files, however, I do get the error.

**Comment by nimble-code** [comment]
retested with the cobra.exe from the distribution on the cobra sources *.[ch] but don't get the problem.
if you have a sample file that triggers the bug, can you send it to me?  gerard.holzmann@gmail.com

**Comment by keck-in-space** [comment]
Interesting. I can't send any code from the project I'm analyzing, unfortunately, but I can see if I can generate a file that produces this issue. Thanks!

**Comment by keck-in-space** [comment]
I'm guessing there was something wrong with my test setup because I can no longer generate the error on the simple case I had above. The error still occurs with the original source files that I have been analyzing. Here is the output with the printf you mentioned.

```
s: s c_base: /
assertion "strlen(c)+strlen(f->s) < n" failed: file "cobra_prim.c", line 237, function: check_args
Aborted (core dumped)
```

**Comment by nimble-code** [comment]
if the argument s is really equal to "s" then
the 3 strstr calls at the start of the function will all return 0
and the function will return s immediately, and not get to the
failing assertion....

**Comment by keck-in-space** [comment]
Very curious. Are there any other printfs I can grab that would help figure out the cause of this assertion failure?

**Comment by nimble-code** [comment]
No that printf should tell us what's going on -- but the value of argument 's' has to contain the macros that are expanded, or else the assertion isn't reached.  can you check?

**Comment by nimble-code** [comment]
closing this issue as not reproducible -- please resubmit if it reoccurs and there's an example to reproduce the behavior

**Comment by keck-in-space** [comment]
I just tried the latest Cobra release on the source of [FreeRTOS](https://www.freertos.org/a00104.html#getting-started) v10.2.1 and I see the error there.

```
:p10_rule6b
assertion "strlen(c)+strlen(f->s) < n" failed: file "cobra_prim.c", line 225, function: check_args
Aborted (core dumped)
```

**Comment by keck-in-space** [comment]
I suppose it's possible I've misconfigured Cobra. All I have to do to see the error with FreeRTOS is place the contents of the Source/include directory into the Source directory and run the p10 rule set on that folder.

**Comment by nimble-code** [comment]
Ah, yes, I can reproduce it now. Thanks!
I'll look into it and will fix it.

**Comment by keck-in-space** [comment]
Thanks! I was happy to find an open-source code base where the error occurred. Best of luck! I'm still thinking it is possibly due to my setup (cygwin on win10). Let me know if I can provide more information.

**Comment by nimble-code** [comment]
I believe this is now fixed. new files uploaded.
The underlying issue was that when none of the input files can successfully be preprocessed (which the p10 rules do by default), then there are 0 files to process, which led to the unusual case trapped in the assertion.
this is now fixed -- cobra will now just terminate with an error, after reporting all the compiler errors on the incomplete input provided.
to prevent the default invocation of cpp in the p10 rules, add the command-line argument -nocpp
as in, for instance:
cobra -I./include -nocpp -f p10 *.c

**Comment by keck-in-space** [comment]
I can confirm the issue is fixed in the latest commit for my source as well. Thanks so much!
